import type { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import { z } from "../../openapi/zod.js";
const summary = z.object({ provider: z.string(), id: z.string(), sourceRevision: z.string(), manufacturer: z.string(), model: z.string(), slug: z.string(), partNumber: z.string().nullable(), uHeight: z.number().nullable(), frontImageAvailable: z.boolean(), rearImageAvailable: z.boolean() });
export function registerCatalogOpenApi(registry: OpenAPIRegistry) {
  registry.registerPath({ method: "get", path: "/api/v1/catalog/device-types", tags: ["Catalog"], security: [{ cookieAuth: [] }], request: { query: z.object({ q: z.string().optional(), manufacturer: z.string().optional(), uHeight: z.coerce.number().optional(), hasFrontImage: z.enum(["true", "false"]).optional(), hasRearImage: z.enum(["true", "false"]).optional(), limit: z.coerce.number().optional(), offset: z.coerce.number().optional() }) }, responses: { 200: { description: "Catalog device summaries", content: { "application/json": { schema: z.array(summary) } } } } });
  registry.registerPath({ method: "get", path: "/api/v1/catalog/providers", tags: ["Catalog"], security: [{ cookieAuth: [] }], responses: { 200: { description: "Catalog providers", content: { "application/json": { schema: z.array(z.object({ id: z.string(), name: z.string(), revision: z.string() })) } } } } });
  registry.registerPath({ method: "get", path: "/api/v1/catalog/device-types/{id}", tags: ["Catalog"], security: [{ cookieAuth: [] }], request: { params: z.object({ id: z.string() }) }, responses: { 200: { description: "Catalog device detail" }, 404: { description: "Catalog device not found" } } });
  registry.registerPath({ method: "get", path: "/api/v1/catalog/manufacturers", tags: ["Catalog"], security: [{ cookieAuth: [] }], responses: { 200: { description: "Catalog manufacturers", content: { "application/json": { schema: z.array(z.object({ name: z.string(), deviceCount: z.number() })) } } } } });
}
