import type { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import { z } from "../../openapi/zod.js";

export function registerDeviceImageOpenApi(registry: OpenAPIRegistry) {
    const params = z.object({ assetId: z.uuid(), side: z.enum(["front", "rear"]) });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}/urls", tags: ["Device images"], summary: "Create expiring URLs for a device's front and rear images", security: [{ bearerAuth: [] }], request: { params: z.object({ assetId: z.uuid() }) }, responses: { 200: { description: "Signed image URLs", content: { "application/json": { schema: z.object({ front: z.string(), rear: z.string() }) } } }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}/{side}/{expires}/{nonce}/{signature}", tags: ["Device images"], summary: "Fetch a cached or default device elevation image using a signed URL", request: { params: params.extend({ expires: z.coerce.number().int(), nonce: z.string(), signature: z.string() }) }, responses: { 200: { description: "PNG, JPEG, or WebP image", content: { "image/png": { schema: z.string().openapi({ format: "binary" }) }, "image/jpeg": { schema: z.string().openapi({ format: "binary" }) }, "image/webp": { schema: z.string().openapi({ format: "binary" }) } } }, 401: { description: "Invalid or expired image URL" }, 404: { description: "No image or asset found" } } });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}", tags: ["Device images"], summary: "Check custom image overrides", security: [{ bearerAuth: [] }], request: { params: z.object({ assetId: z.uuid() }) }, responses: { 200: { description: "Custom override availability", content: { "application/json": { schema: z.object({ front: z.boolean(), rear: z.boolean() }) } } }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "put", path: "/api/v1/device-images/{assetId}/{side}", tags: ["Device images"], summary: "Upload a custom device elevation image", security: [{ bearerAuth: [] }], request: { params, body: { required: true, content: { "image/png": { schema: z.string().openapi({ format: "binary" }) }, "image/jpeg": { schema: z.string().openapi({ format: "binary" }) }, "image/webp": { schema: z.string().openapi({ format: "binary" }) } } } }, responses: { 200: { description: "Custom override saved", content: { "application/json": { schema: z.object({ side: z.enum(["front", "rear"]), contentType: z.string(), source: z.literal("custom") }) } } }, 400: { description: "Invalid image" }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "delete", path: "/api/v1/device-images/{assetId}/{side}", tags: ["Device images"], summary: "Remove a custom device image override", security: [{ bearerAuth: [] }], request: { params }, responses: { 204: { description: "Custom override removed" }, 401: { description: "Authentication required" } } });
}
