import type { OpenAPIRegistry } from "@asteasolutions/zod-to-openapi";
import { z } from "../../openapi/zod.js";

export function registerDeviceImageOpenApi(registry: OpenAPIRegistry) {
    registry.registerPath({ method: "get", path: "/api/v1/device-images/catalog", tags: ["Device images"], summary: "Search the NetBox device image catalog", security: [{ cookieAuth: [] }], request: { query: z.object({ q: z.string().min(2).max(100) }) }, responses: { 200: { description: "Matching catalog images", content: { "application/json": { schema: z.array(z.object({ path: z.string(), side: z.enum(["front", "rear"]), label: z.string(), rawUrl: z.string() })) } } }, 400: { description: "Search query is too short" }, 401: { description: "Authentication required" } } });
    const params = z.object({ assetId: z.uuid(), side: z.enum(["front", "rear"]) });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/library", tags: ["Device images"], summary: "List previously uploaded asset images", security: [{ cookieAuth: [] }], responses: { 200: { description: "Uploaded images with signed preview URLs", content: { "application/json": { schema: z.array(z.object({ assetId: z.uuid(), assetName: z.string(), side: z.enum(["front", "rear"]), previewUrl: z.string() })) } } }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "post", path: "/api/v1/device-images/{assetId}/{side}/from-asset", tags: ["Device images"], summary: "Copy a previously uploaded image to an asset", security: [{ cookieAuth: [] }], request: { params, body: { required: true, content: { "application/json": { schema: z.object({ sourceAssetId: z.uuid(), sourceSide: z.enum(["front", "rear"]) }) } } } }, responses: { 200: { description: "Uploaded image copied", content: { "application/json": { schema: z.object({ side: z.enum(["front", "rear"]), contentType: z.string(), source: z.literal("custom") }) } } }, 400: { description: "Invalid request" }, 401: { description: "Authentication required" }, 404: { description: "Source image or asset not found" } } });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}/urls", tags: ["Device images"], summary: "Create expiring URLs for a device's front and rear images", security: [{ cookieAuth: [] }], request: { params: z.object({ assetId: z.uuid() }) }, responses: { 200: { description: "Signed image URLs", content: { "application/json": { schema: z.object({ front: z.string(), rear: z.string() }) } } }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}/{side}/{expires}/{nonce}/{signature}", tags: ["Device images"], summary: "Fetch a cached or default device elevation image using a signed URL", request: { params: params.extend({ expires: z.coerce.number().int(), nonce: z.string(), signature: z.string() }) }, responses: { 200: { description: "PNG, JPEG, or WebP image", content: { "image/png": { schema: z.string().openapi({ format: "binary" }) }, "image/jpeg": { schema: z.string().openapi({ format: "binary" }) }, "image/webp": { schema: z.string().openapi({ format: "binary" }) } } }, 401: { description: "Invalid or expired image URL" }, 404: { description: "No image or asset found" } } });
    registry.registerPath({ method: "get", path: "/api/v1/device-images/{assetId}", tags: ["Device images"], summary: "Check custom image overrides", security: [{ cookieAuth: [] }], request: { params: z.object({ assetId: z.uuid() }) }, responses: { 200: { description: "Custom override availability", content: { "application/json": { schema: z.object({ front: z.boolean(), rear: z.boolean() }) } } }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "put", path: "/api/v1/device-images/{assetId}/{side}", tags: ["Device images"], summary: "Upload a custom device elevation image", security: [{ cookieAuth: [] }], request: { params, body: { required: true, content: { "image/png": { schema: z.string().openapi({ format: "binary" }) }, "image/jpeg": { schema: z.string().openapi({ format: "binary" }) }, "image/webp": { schema: z.string().openapi({ format: "binary" }) } } } }, responses: { 200: { description: "Custom override saved", content: { "application/json": { schema: z.object({ side: z.enum(["front", "rear"]), contentType: z.string(), source: z.literal("custom") }) } } }, 400: { description: "Invalid image" }, 401: { description: "Authentication required" } } });
    registry.registerPath({ method: "post", path: "/api/v1/device-images/{assetId}/{side}/catalog", tags: ["Device images"], summary: "Select a catalog image as an asset override", security: [{ cookieAuth: [] }], request: { params, body: { required: true, content: { "application/json": { schema: z.object({ path: z.string().min(1).max(500) }) } } } }, responses: { 200: { description: "Catalog image selected" }, 400: { description: "Invalid catalog image" }, 401: { description: "Authentication required" }, 502: { description: "Catalog image download failed" } } });
    registry.registerPath({ method: "delete", path: "/api/v1/device-images/{assetId}/{side}", tags: ["Device images"], summary: "Remove a custom device image override", security: [{ cookieAuth: [] }], request: { params }, responses: { 204: { description: "Custom override removed" }, 401: { description: "Authentication required" } } });
}
