import { Router } from "express";
import { z } from "../../openapi/zod.js";
import { createAddressSchema, createConnectionSchema, createInterfaceSchema, createPortSchema, updateAddressSchema, updateConnectionSchema, updateInterfaceSchema, updatePortSchema } from "./network.schema.js";
import { networkService as service } from "./network.service.js";
const id = (value: string | undefined) => z.uuid().parse(value);
export const networkAssetRouter = Router();
networkAssetRouter.get("/:assetId/interfaces", async (req, res) => { res.json(await service.interfaces(id(req.params.assetId))); });
networkAssetRouter.post("/:assetId/interfaces", async (req, res) => { res.status(201).json(await service.createInterface(id(req.params.assetId), createInterfaceSchema.parse(req.body))); });
networkAssetRouter.get("/:assetId/ports", async (req, res) => { res.json(await service.ports(id(req.params.assetId))); });
networkAssetRouter.post("/:assetId/ports", async (req, res) => { res.status(201).json(await service.createPort(id(req.params.assetId), createPortSchema.parse(req.body))); });
export const interfaceRouter = Router();
interfaceRouter.get("/", async (req, res) => { const query = z.object({ assetId: z.uuid().optional() }).strict().parse(req.query); res.json(await service.interfaces(query.assetId)); });
interfaceRouter.get("/:id", async (req, res) => { res.json(await service.interface(id(req.params.id))); });
interfaceRouter.patch("/:id", async (req, res) => { res.json(await service.updateInterface(id(req.params.id), updateInterfaceSchema.parse(req.body))); });
interfaceRouter.delete("/:id", async (req, res) => { await service.deleteInterface(id(req.params.id)); res.status(204).send(); });
interfaceRouter.get("/:interfaceId/ip-addresses", async (req, res) => { res.json(await service.addresses(id(req.params.interfaceId))); });
interfaceRouter.post("/:interfaceId/ip-addresses", async (req, res) => { res.status(201).json(await service.addAddress(id(req.params.interfaceId), createAddressSchema.parse(req.body))); });
export const portRouter = Router();
portRouter.get("/", async (req, res) => { const query = z.object({ assetId: z.uuid().optional() }).strict().parse(req.query); res.json(await service.ports(query.assetId)); });
portRouter.get("/:id", async (req, res) => { res.json(await service.port(id(req.params.id))); });
portRouter.patch("/:id", async (req, res) => { res.json(await service.updatePort(id(req.params.id), updatePortSchema.parse(req.body))); });
portRouter.delete("/:id", async (req, res) => { await service.deletePort(id(req.params.id)); res.status(204).send(); });
export const connectionRouter = Router();
connectionRouter.get("/", async (req, res) => { const query = z.object({ assetId: z.uuid().optional(), portId: z.uuid().optional() }).strict().parse(req.query); res.json(await service.connections(query.assetId, query.portId)); });
connectionRouter.get("/:id", async (req, res) => { res.json(await service.connection(id(req.params.id))); });
connectionRouter.post("/", async (req, res) => { res.status(201).json(await service.connect(createConnectionSchema.parse(req.body))); });
connectionRouter.patch("/:id", async (req, res) => { res.json(await service.updateConnection(id(req.params.id), updateConnectionSchema.parse(req.body))); });
connectionRouter.delete("/:id", async (req, res) => { await service.disconnect(id(req.params.id)); res.status(204).send(); });
export const addressRouter = Router();
addressRouter.get("/", async (_req, res) => { res.json(await service.addresses()); });
addressRouter.patch("/:id", async (req, res) => { res.json(await service.updateAddress(id(req.params.id), updateAddressSchema.parse(req.body))); });
addressRouter.delete("/:id", async (req, res) => { await service.deleteAddress(id(req.params.id)); res.status(204).send(); });
