import { z } from "../../openapi/zod.js";
export const componentStatusSchema = z.enum(["installed", "spare", "planned", "retired", "failed"]);
export const componentTypeSchema = z.object({ id: z.uuid(), name: z.string(), slug: z.string(), description: z.string().nullable(), builtIn: z.boolean(), createdAt: z.iso.datetime(), updatedAt: z.iso.datetime() });
export const createComponentTypeSchema = z.object({ name: z.string().trim().min(1), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/), description: z.string().nullable().optional() }).strict();
export const componentSchema = z.object({ id: z.uuid(), assetId: z.uuid().nullable(), componentTypeId: z.uuid(), locationId: z.uuid().nullable(), name: z.string(), manufacturer: z.string().nullable(), model: z.string().nullable(), partNumber: z.string().nullable(), serialNumber: z.string().nullable(), quantity: z.number().int(), status: componentStatusSchema, attributes: z.record(z.string(), z.unknown()), storageLocation: z.string().nullable(), installedAt: z.iso.datetime().nullable(), removedAt: z.iso.datetime().nullable(), notes: z.string().nullable(), createdAt: z.iso.datetime(), updatedAt: z.iso.datetime() });
export const createComponentSchema = z.object({ assetId: z.uuid().nullable().optional(), componentTypeId: z.uuid(), locationId: z.uuid().nullable().optional(), name: z.string().trim().min(1), manufacturer: z.string().nullable().optional(), model: z.string().nullable().optional(), partNumber: z.string().nullable().optional(), serialNumber: z.string().nullable().optional(), quantity: z.number().int().positive().optional(), status: componentStatusSchema, attributes: z.record(z.string(), z.unknown()).optional(), storageLocation: z.string().nullable().optional(), installedAt: z.iso.datetime({ offset: true }).nullable().optional(), removedAt: z.iso.datetime({ offset: true }).nullable().optional(), notes: z.string().nullable().optional() }).strict();
export const updateComponentSchema = createComponentSchema.partial();
export const componentFilterSchema = z.object({ assetId: z.uuid().optional(), componentTypeId: z.uuid().optional(), status: componentStatusSchema.optional(), unassigned: z.enum(["true", "false"]).optional() }).strict();

export type CreateComponent = z.infer<typeof createComponentSchema>;
export type UpdateComponent = z.infer<typeof updateComponentSchema>;
